# Waze Traffic Forecast Configuration

# Data settings
data:
  directory: /Users/charlottejackson/waze_forecast_data
  sample_size: 10000  # Set to a number for development/testing
  interval_minutes: 15
  max_snapshots: 100  # Reduced for local testing
  train_ratio: 0.7
  val_ratio: 0.15
  test_ratio: 0.15
  sequence_length: 12  # Number of historical steps
  prediction_horizon: 3  # Number of future steps to predict
  feature_columns:
    - speed
    - severity
    - delay
    - length
    - is_accident_related      # NEW: Boolean flag (0/1)
    - time_since_accident      # NEW: Minutes since accident was reported
  
  # NEW: Accident processing parameters
  accident_processing:
    max_accident_duration: 180    # Consider accident active for 3 hours max
    time_decay_factor: 0.95      # Exponential decay of accident influence
    enable_accident_features: true
  # Graph sampling options
  full_graph: false  # Set to false for sparse subgraph training (better for local testing)
  subgraph_nodes: 1000  # Maximum nodes for subgraph sampling (reduced for local testing)
  batch_size: 100  # Mini-batch size for full graph training
  num_hops: 2  # Number of hops for neighborhood sampling

# Model settings
model:
  name: STGformer
  hidden_channels: 64
  num_layers: 3
  num_heads: 8
  dropout: 0.1
  attention_dropout: 0.1
  use_layer_norm: true
  use_residual: true
  propagation_steps: 2  # Number of graph propagation hops

# Training settings
training:
  batch_size: 16  # Reduced for local testing
  learning_rate: 1.0e-3
  weight_decay: 1.0e-4
  num_epochs: 10  # Reduced for local testing
  patience: 5  # Early stopping patience
  lr_scheduler: cosine  # Options: step, cosine, plateau
  lr_scheduler_params:
    step_size: 10
    gamma: 0.1
    factor: 0.5
    patience: 5
  grad_clip_value: 5.0
  device: auto  # Options: auto, cuda, cpu

# Paths
paths:
  output_dir: ./output
  checkpoint_dir: ./checkpoints
  log_dir: ./logs