# Waze Traffic Forecast Configuration

data:
  directory: /scratch/mj6ux/data/waze
  sample_size: null 
  interval_minutes: 15
  max_snapshots: 1000
  train_ratio: 0.7
  val_ratio: 0.15
  test_ratio: 0.15
  sequence_length: 12 
  prediction_horizon: 3 
  feature_columns:
    - speed
    - severity
    - delay
    - length

model:
  name: STGformer
  hidden_channels: 64
  num_layers: 3
  num_heads: 8
  dropout: 0.1
  attention_dropout: 0.1
  use_layer_norm: true
  use_residual: true

training:
  batch_size: 32
  learning_rate: 1.0e-3
  weight_decay: 1.0e-4
  num_epochs: 100
  patience: 10  
  lr_scheduler: cosine
  lr_scheduler_params:
    step_size: 10
    gamma: 0.1
    factor: 0.5
    patience: 5
  grad_clip_value: 5.0
  device: auto 

paths:
  output_dir: ./output
  checkpoint_dir: ./checkpoints
  log_dir: ./logs