name: waze-traffic
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip>=23.0
  - setuptools>=68.0
  - pandas>=2.0.0
  - numpy>=1.24.0
  - matplotlib>=3.7.0
  - networkx>=3.1
  - scikit-learn>=1.2.0
  - tqdm>=4.65.0
  - pytz>=2023.3
  - pyyaml>=6.0
  - pytorch>=2.1.0
  - pytorch-cuda=12.1
  - torchvision>=0.16.0
  - pyarrow>=14.0.0
  - fastparquet>=2023.10.0
  - black>=23.10.0
  - flake8>=6.1.0
  - isort>=5.12.0
  - pytest>=7.4.0
  - pytest-cov>=4.1.0
  - jupyter>=1.0.0
  - jupyterlab>=4.0.0
  - ipywidgets>=8.1.0
  - seaborn>=0.13.0
  - plotly>=5.18.0
  - pip:
    - wandb>=0.16.0
    - accelerate>=0.24.0
    - tensorboard>=2.15.0
    - torch-geometric>=2.4.0
    - einops>=0.7.0 
    - rich>=13.6.0      
    - typer>=0.9.0      
    - pydantic>=2.5.0   
    - -e .                  