name: waze-traffic
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - comm=0.2.2
  - debugpy=1.8.12
  - decorator=5.2.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - importlib-metadata=8.6.1
  - ipykernel=6.29.5
  - ipython=9.0.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - keyutils=1.6.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.43
  - libedit=3.1.20250104
  - libexpat=2.6.4
  - libffi=3.4.6
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - liblzma=5.6.4
  - libnsl=2.0.1
  - libsodium=1.0.20
  - libsqlite=3.49.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - matplotlib-inline=0.1.7
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.4.1
  - packaging=24.2
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.0.1
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.50
  - psutil=7.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - python=3.12.9
  - python-dateutil=2.9.0.post0
  - python_abi=3.12
  - pyzmq=26.2.1
  - readline=8.2
  - setuptools=75.8.0
  - six=1.17.0
  - stack_data=0.6.3
  - tk=8.6.13
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - wheel=0.45.1
  - zeromq=4.3.5
  - zipp=3.21.0
  - pip:
      - accelerate==1.5.2
      - aiohappyeyeballs==2.4.6
      - aiohttp==3.11.13
      - aiosignal==1.3.2
      - airportsdata==20250224
      - annotated-types==0.7.0
      - anthropic==0.49.0
      - anyio==4.9.0
      - astor==0.8.1
      - attrs==25.1.0
      - backoff==2.2.1
      - blake3==1.0.4
      - cachetools==5.5.2
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cloudpickle==3.1.1
      - compressed-tensors==0.9.2
      - cupy-cuda12x==13.4.0
      - dataclasses-json==0.6.7
      - datasets==3.1.0
      - depyf==0.18.0
      - dill==0.3.8
      - diskcache==5.6.3
      - distro==1.9.0
      - dnspython==2.7.0
      - docker-pycreds==0.4.0
      - einops==0.8.1
      - email-validator==2.2.0
      - eval-type-backport==0.2.2
      - fastapi==0.115.11
      - fastapi-cli==0.0.7
      - fastrlock==0.8.3
      - filelock==3.17.0
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - gguf==0.10.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - greenlet==3.1.1
      - h11==0.14.0
      - httpcore==1.0.7
      - httptools==0.6.4
      - httpx==0.28.1
      - httpx-sse==0.4.0
      - huggingface-hub==0.29.1
      - idna==3.10
      - interegular==0.3.3
      - jinja2==3.1.5
      - jiter==0.9.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - langchain==0.3.21
      - langchain-community==0.3.20
      - langchain-core==0.3.47
      - langchain-text-splitters==0.3.7
      - langsmith==0.3.18
      - lark==1.2.2
      - llvmlite==0.43.0
      - lm-format-enforcer==0.10.11
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - marshmallow==3.26.1
      - mdurl==0.1.2
      - mistral-common==1.5.4
      - mistralai==1.6.0
      - mpmath==1.3.0
      - msgpack==1.1.0
      - msgspec==0.19.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - mypy-extensions==1.0.0
      - networkx==3.4.2
      - ninja==1.11.1.3
      - numba==0.60.0
      - numexpr==2.10.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - openai==1.67.0
      - opencv-python-headless==4.11.0.86
      - orjson==3.10.15
      - outlines==0.1.11
      - outlines-core==0.1.26
      - pandas==2.2.3
      - partial-json-parser==0.2.1.1.post5
      - pillow==11.1.0
      - prometheus-client==0.21.1
      - prometheus-fastapi-instrumentator==7.1.0
      - propcache==0.3.0
      - protobuf==5.29.3
      - py-cpuinfo==9.0.0
      - pyarrow==19.0.1
      - pycountry==24.6.1
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydantic-settings==2.8.1
      - python-dotenv==1.0.1
      - python-json-logger==3.3.0
      - python-multipart==0.0.20
      - pytz==2025.1
      - pyyaml==6.0.2
      - ray==2.43.0
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - rich==13.9.4
      - rich-toolkit==0.13.2
      - rpds-py==0.23.1
      - safetensors==0.5.3
      - scipy==1.15.2
      - sentencepiece==0.2.0
      - sentry-sdk==2.22.0
      - setproctitle==1.3.5
      - shellingham==1.5.4
      - smmap==5.0.2
      - sniffio==1.3.1
      - sqlalchemy==2.0.39
      - starlette==0.46.1
      - sympy==1.13.1
      - tenacity==9.0.0
      - tiktoken==0.9.0
      - tokenizers==0.21.1
      - torch==2.6.0
      - torchaudio==2.6.0
      - torchvision==0.21.0
      - tqdm==4.67.0
      - transformers==4.49.0
      - triton==3.2.0
      - trl==0.16.0.dev0
      - typer==0.15.2
      - typing-inspect==0.9.0
      - typing-inspection==0.4.0
      - tzdata==2025.1
      - urllib3==2.3.0
      - uvicorn==0.34.0
      - uvloop==0.21.0
      - vllm==0.8.1
      - wandb==0.18.7
      - watchfiles==1.0.4
      - websockets==15.0.1
      - xformers==0.0.29.post2
      - xgrammar==0.1.16
      - xxhash==3.5.0
      - yarl==1.18.3
      - zstandard==0.23.0
      - -e .
